INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR SEQ_AUTHOR, 'Behrooz', 'Mohamadi');
INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR SEQ_AUTHOR, 'Martin', 'fowler');

INSERT INTO BOOK (ID,NAME,PAGE_COUNT, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'Java effective', 100, 1);
INSERT INTO BOOK (ID,NAME,PAGE_COUNT, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'Spring tutorial', 100, 1);
INSERT INTO BOOK (ID,NAME,PAGE_COUNT, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'C# tutorial', 100, 2);
