INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR SEQ_AUTHOR, 'Behrooz', 'Mohamadi');
INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (NEXT VALUE FOR SEQ_AUTHOR, 'Martin', 'fowler');

INSERT INTO BOOK (ID,TITLE,PAGE_COUNT,ISBN, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'Java effective', 100,'978-1-4028-9462-6', 1);
INSERT INTO BOOK (ID,TITLE,PAGE_COUNT,ISBN, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'Spring tutorial', 100,'978-0-545-01022-1', 1);
INSERT INTO BOOK (ID,TITLE,PAGE_COUNT,ISBN, AUTHOR_ID) VALUES (NEXT VALUE FOR SEQ_BOOK, 'C# tutorial', 100,'978-3-16-148410-0', 2);
